[package]
name = "rem"
version = "0.1.0"
edition = "2021"

[dependencies]
home = "0.5.9"
serde = {version = "1.0.215", features = ["derive"]}
serde_json = "1.0.133"
clap = { version = "4.5.21", features = ["derive"] }
